sensor:

  # Header Outdoor Temperate
  - platform: homeassistant
    entity_id: sensor.upstairs_humidity
    id: upstairs_humidity
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d%%"
            args: [ '(int)round(id(upstairs_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.upstairs_temperature
    id: upstairs_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d%%"
            args: [ '(int)round(x)', '(int)round(id(upstairs_humidity).state)' ]


  # Office Blind Position
  - platform: homeassistant
    entity_id: cover.office_blind
    id: office_blind_position
    attribute: current_position





binary_sensor:





  # Office Features Scene
  - platform: homeassistant
    id: office_scene_features
    entity_id: switch.office_features_stateful_scene
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda return x;

  

  

  

  

  

  

  

  

  