sensor:

  # Downstairs Temperature / Humidity
  - platform: homeassistant
    entity_id: sensor.downstairs_humidity
    id: downstairs_humidity
    trigger_on_initial_state: true
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d%%"
            args: [ '(int)round(id(downstairs_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.downstairs_temperature
    id: downstairs_temperature
    trigger_on_initial_state: true
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d%%"
            args: [ '(int)round(x)', '(int)round(id(downstairs_humidity).state)' ]


  # Office Blind Position
  - platform: homeassistant
    entity_id: cover.office_blind
    id: office_blind_position
    attribute: current_position



binary_sensor:

  # Big Door open
  - platform: homeassistant
    id: big_door_open
    entity_id: cover.big_door
    on_value:
      then:
        lvgl.widget.update:
          id: big_door_open_button
          state:
            checked: !lambda return x == 'open';

  # Office Features Scene
  - platform: homeassistant
    id: office_scene_features
    entity_id: switch.office_features_stateful_scene
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda return x;

  

  

  

  

  

  

  

  

  