sensor:
  - platform: homeassistant
    entity_id: sensor.bbq_esphome_esphome_bbq_pit_temperature
    id: bbq_pit_temperature
    on_value:
      - lvgl.label.update:
          id: pit_temperature_label
          text:
            format: "%.0f°"
            args: [ 'x' ]
      - lvgl.arc.update:
          id: pit_temperature_arc
          value: !lambda return (int)roundf(x);

  - platform: homeassistant
    entity_id: sensor.bbq_esphome_esphome_bbq_pit_fan_output
    id: bbq_fan_output
    on_value:
      - lvgl.label.update:
          id: fan_output_label
          text:
            format: "%.0f%%"
            args: [ 'x' ]

  - platform: homeassistant
    entity_id: ${climate_entity}
    id: bbq_target_temperature
    attribute: temperature
    on_value:
      - lvgl.label.update:
          id: target_temperature_label
          text:
            format: "%.0f°"
            args: [ 'x' ]
      - lvgl.arc.update:
          id: target_temperature_arc
          value: !lambda return (int)roundf(x);

text_sensor:
  - platform: homeassistant
    entity_id: ${climate_entity}
    id: bbq_hvac_mode
    on_value:
      - lvgl.label.update:
          id: hvac_mode_label
          text: !lambda |-
            if (x == "heat") return "HEAT";
            if (x == "off") return "OFF";
            return x;
      - lvgl.widget.update:
          id: heat_mode_button
          state:
            checked: !lambda return x == "heat";
